#!/usr/bin/env python3
"""envctl — the env-var automation for plan §3.

One manifest (infra/env-manifest.yaml) drives every environment variable in the
system. No variable is ever hand-typed into a cloud console.

Commands:
  gen-example              Regenerate apps/<svc>/.env.example from the manifest.
  secrets   --env ENV      Print the Secret Manager secrets that must exist.
  set-env   --env ENV --region R [--service S] [--apply]
                           Push config vars + secret bindings to Cloud Run.
                           Prints the exact gcloud commands; --apply executes.

Adding a variable is a one-line edit to the manifest plus `make set-env ENV=...`.

Secrets are bound by *reference* (KEY=projects/P/secrets/S:latest), so a raw
secret value never passes through this script, the shell history, or CI logs.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("envctl: PyYAML missing. Run `make bootstrap`.")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "infra" / "env-manifest.yaml"

VALID_ENVS = ("dev", "staging", "prod")

# Non-secret, per-env values that the manifest interpolates via ${...}. These are
# outputs of Terraform (§5.2) — in CI they arrive as env vars from `terraform
# output`, so the placeholders resolve automatically.
INTERPOLATED = (
    "ENV", "REGION", "QDRANT_URL", "ML_SERVICE_URL", "R2_ENDPOINT",
    "OTEL_ENDPOINT", "ADMIN_EMAILS", "TEMPORAL_HOST", "API_BASE",
    "APP_BASE_URL", "CLARITY_ID", "SUPABASE_URL", "SUPABASE_ANON_KEY",
)


def load_manifest() -> dict:
    with MANIFEST.open() as fh:
        return yaml.safe_load(fh)


class UnresolvedError(Exception):
    """A ${PLACEHOLDER} had no value. Fatal outside dev: shipping an empty
    ML_SERVICE_URL or QDRANT_URL to prod is an outage, not a warning."""


def resolve(var: dict, env: str, region: str, strict: bool = False) -> str:
    """Resolve a config var's literal value for a given env/region.

    Placeholders resolve from the process env, which in CI is populated by
    `terraform output` (§5.2). When `strict`, an unresolved placeholder raises
    rather than silently producing an empty value.
    """
    if "values" in var:
        if env not in var["values"]:
            raise KeyError(f"{var['key']}: no value defined for env '{env}'")
        raw = str(var["values"][env])
    else:
        raw = str(var.get("value", ""))

    ctx = {"ENV": env, "REGION": region}
    for name in INTERPOLATED:
        ctx.setdefault(name, os.environ.get(name, ""))

    missing: list[str] = []

    def sub(m: re.Match) -> str:
        val = ctx.get(m.group(1), "")
        if not val:
            missing.append(m.group(1))
        return val

    out = re.sub(r"\$\{(\w+)\}", sub, raw)

    if strict and missing:
        raise UnresolvedError(
            f"{var['key']}: unresolved placeholder(s) {', '.join(missing)} — "
            f"expected them in the environment (from `terraform output`)"
        )
    return out


def cmd_gen_example(_args: argparse.Namespace) -> int:
    manifest = load_manifest()
    for svc, spec in manifest["services"].items():
        path = ROOT / "apps" / svc / ".env.example"
        if not path.parent.exists():
            continue
        lines = [
            f"# {svc} — {spec.get('description', '')}",
            "#",
            "# GENERATED by scripts/envctl.py from infra/env-manifest.yaml.",
            "# Do not edit by hand; edit the manifest and run `make env-example`.",
            "#",
            "# Values shown are the dev defaults. Secrets are intentionally BLANK:",
            "# they come from Secret Manager in every deployed environment (§4).",
            "",
        ]
        for var in spec["vars"]:
            if var["type"] == "secret":
                lines.append(f"# secret -> Secret Manager: {var['secret']}")
                lines.append(f"{var['key']}=")
            else:
                try:
                    val = resolve(var, "dev", "local")
                except KeyError:
                    val = ""
                lines.append(f"{var['key']}={val}")
        lines.append("")
        path.write_text("\n".join(lines))
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def cmd_secrets(args: argparse.Namespace) -> int:
    manifest = load_manifest()
    names = sorted({
        v["secret"]
        for spec in manifest["services"].values()
        for v in spec["vars"]
        if v["type"] == "secret"
    })
    print(f"# {len(names)} secrets required for env '{args.env}'.")
    print("# Create each once, then add its value as a version:")
    for n in names:
        full = f"{n}-{args.env}"
        print(f"gcloud secrets create {full} --replication-policy=automatic")
        print(f"  # then: echo -n '<value>' | gcloud secrets versions add {full} --data-file=-")
    return 0


def cmd_set_env(args: argparse.Namespace) -> int:
    manifest = load_manifest()
    services = [args.service] if args.service else list(manifest["services"])

    failed = False
    for svc in services:
        spec = manifest["services"].get(svc)
        if spec is None:
            print(f"envctl: unknown service '{svc}'", file=sys.stderr)
            return 2
        if spec.get("platform") == "vercel":
            print(f"# skipping '{svc}': deployed via Vercel CLI, not Cloud Run")
            continue

        # dev tolerates unset placeholders (no cloud resources exist yet);
        # staging/prod must resolve every one.
        strict = args.env != "dev"

        env_vars, secret_refs = [], []
        problems: list[str] = []
        for var in spec["vars"]:
            if var["type"] == "secret":
                secret_refs.append(
                    f"{var['key']}=projects/{args.project}/secrets/{var['secret']}-{args.env}:latest"
                )
            else:
                try:
                    env_vars.append(
                        f"{var['key']}={resolve(var, args.env, args.region, strict=strict)}"
                    )
                except (KeyError, UnresolvedError) as e:
                    problems.append(str(e))

        # Report every problem for this service at once, so one run tells you
        # everything to fix instead of failing on the first bad var.
        if problems:
            print(f"envctl: cannot configure '{svc}' for env '{args.env}':", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            failed = True
            continue

        service_name = f"prooftamil-{svc}-{args.env}"
        cmd = [
            "gcloud", "run", "services", "update", service_name,
            "--region", args.region,
            "--project", args.project,
            # ^-delimited so values containing commas (MODEL_ROUTER_CONFIG is
            # JSON) survive gcloud's default comma splitting.
            "--set-env-vars", "^@^" + "@".join(env_vars),
        ]
        if secret_refs:
            cmd += ["--set-secrets", "^@^" + "@".join(secret_refs)]

        print(f"\n# --- {service_name} ({len(env_vars)} config, {len(secret_refs)} secrets) ---")
        print(" ".join(cmd))

        if args.apply:
            result = subprocess.run(cmd)
            if result.returncode != 0:
                print(f"envctl: FAILED to update {service_name}", file=sys.stderr)
                failed = True

    if failed:
        return 1
    if not args.apply:
        print("\n# dry run — no changes made. Re-run with --apply to execute.")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(prog="envctl", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("gen-example").set_defaults(fn=cmd_gen_example)

    s = sub.add_parser("secrets")
    s.add_argument("--env", required=True, choices=VALID_ENVS)
    s.set_defaults(fn=cmd_secrets)

    e = sub.add_parser("set-env")
    e.add_argument("--env", required=True, choices=VALID_ENVS)
    e.add_argument("--region", required=True)
    e.add_argument("--project", default=None)
    e.add_argument("--service", default=None)
    e.add_argument("--apply", action="store_true",
                   help="execute the gcloud commands (default: dry run)")
    e.set_defaults(fn=cmd_set_env)

    args = p.parse_args()
    if getattr(args, "project", None) is None and args.cmd == "set-env":
        args.project = os.environ.get("GCP_PROJECT") or f"prooftamil-{args.env}"
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
