variable "project_id" {
  type        = string
  description = "GCP project id (reuse your existing v1 project)."
}

variable "region" {
  type        = string
  description = "Cloud Run region."
  default     = "asia-south1"
}

variable "github_owner" {
  type        = string
  description = "GitHub owner/org of the v2 repo."
  default     = "palkani"
}

variable "github_repo" {
  type        = string
  description = "GitHub repo name that runs the deploy workflow."
  default     = "prooftamil"
}

variable "deployer_sa_email" {
  type        = string
  description = <<-EOT
    Email of the EXISTING deploy service account (the one v1 already uses).
    Terraform mints a fresh JSON key for it and pushes it as the GCP_SA_KEY
    secret — v1's key is untouched. e.g. gh-deployer@PROJECT.iam.gserviceaccount.com
  EOT
}

variable "runtime_sa_email" {
  type        = string
  description = <<-EOT
    The service account the Cloud Run services RUN AS (and therefore read secrets
    as). Leave empty to use the project's default Compute Engine SA.
  EOT
  default     = ""
}

# ── App secret VALUES (sensitive). Provide via terraform.tfvars or TF_VAR_*. ──
# The JWT keypair is generated by Terraform (tls_private_key), not passed in.

variable "gemini_api_key" {
  type        = string
  description = "Gemini API key (same one v1 uses is fine)."
  sensitive   = true
}

variable "database_url" {
  type        = string
  description = "Postgres connection URL for the api (Supabase)."
  sensitive   = true
}

variable "redis_url" {
  type        = string
  description = "Redis URL for the api cache (Upstash)."
  sensitive   = true
}
